[package]
name = "aion"
version = "0.1.0"
authors = ["Gan Jun Kai <kuhn96@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"

[[example]]
name = "example"
path = "example/main.rs"
